spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${aws.db.username}
    password: ${aws.db.password}

  jpa:
    hibernate:
      ddl-auto: update

  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET, POST, PATCH, DELETE, PUT
      allowed-headers: "*"
      allow-credentials: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: umc-7th
      path:
        photo : photos
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${aws.access.key.id}
      secretKey: ${aws.secret.access.key}

